### ISSUE TITLE
Date stamp showing “undefined 12, 2021”

### ISSUE THREAD

**Issue by coreyward** [dennispassway/sanity-plugin-media-library#10]
There seems to be something odd happening with the date stamps. Both the “Created at” column in the list view and the modal view exhibit this behavior:

<img width="106" alt="Screen Shot 2021-01-12 at 2 52 05 PM" src="https://user-images.githubusercontent.com/81224/104372933-cbe5a180-54e5-11eb-8b87-2277a4d85b64.png">

<img width="207" alt="Screen Shot 2021-01-12 at 2 53 04 PM" src="https://user-images.githubusercontent.com/81224/104373002-e91a7000-54e5-11eb-8891-5973bc80bca6.png">

This is in a pretty fresh studio without much tweaking. I'm in the U.S., central timezone, using Firefox, if any of that happens to be useful.

**Comment by dennispassway** [comment]
I will look into this!
