### ISSUE TITLE
File upload(s) don't refresh the media library window once complete.

### ISSUE THREAD

**Issue by anthonysapp** [dennispassway/sanity-plugin-media-library#12]
Steps to reproduce:

- Upload a file / multiple files
- Loading spinner is triggered
- File upload completes, but preview thumbnails don't show up in the media library
- User must refresh the page to view newly uploaded files

**Comment by ovsw** [comment]
I get the same problem.

**Comment by Aratramba** [comment]
Thanks @anthonysapp and @ovsw for reporting. I'm seeing this as well. We'll get if fixed.

**Comment by dennispassway** [comment]
Fixed in https://github.com/dennispassway/sanity-plugin-media-library/pull/15
