### ISSUE TITLE
Set a default sorting method

### ISSUE THREAD

**Issue by Ojay** [dennispassway/sanity-plugin-media-library#27]
Hi there mate, just a quick one about sorting... is there a way to set **Last Created: Oldest first** as the default sort option?

Thanks so much

**Comment by Aratramba** [comment]
this is not possible atm, sorry. We are involved in a lot of other projects right now, but we're happy to look at a pr in this direction.

Just curious: in what scenario do you want to see the oldest files on top by default?

**Comment by Ojay** [comment]
No that's completely fine mate, it was a long shot, thanks for letting me know.
Request was from a client, they're uploading 1,000's of images and are having a tough time of it I think. 

Thanks for getting back to me 👍

**Comment by Aratramba** [comment]
you could use the [other media plugin](https://www.sanity.io/plugins/sanity-plugin-media), this has some pretty great sorting/filtering options. You could even run the two media plugins alongside each other if you'd like all the options available (might confuse the client though 🙂)

![](https://user-images.githubusercontent.com/209129/108927411-21aa7f00-7638-11eb-9cf7-334598ac4103.png)
