### ISSUE TITLE
UI z-index issue

### ISSUE THREAD

**Issue by fabien** [dennispassway/sanity-plugin-media-library#28]
Please see the screenshot below:

![image](https://user-images.githubusercontent.com/2749/115957607-c0057480-a503-11eb-840c-d4e931b2808b.png)

This is running at v. 2.8.1 in a stock Studio with the e-commerce preset.

I think the Modal should open in a Portal, because it is currently inserted into the Asset modal hierarchy.

**Comment by Aratramba** [comment]
Thanks for reporting. This should be fixed in 1.0.7. I bumped the z-index, because we don't want to be dependant on sanity ui (yet).
